# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       picture-frame

# >> macros
# << macros

Summary:    Picture Frame
Version:    1.0
Release:    1
Group:      Amusements/Graphics
License:    GPLv2+
URL:        http://userbase.kde.org/Plasma/PictureFrame
Source0:    %{name}-%{version}.tar.bz2
Source100:  picture-frame.yaml
Requires:   %{kde_runtime_requires}
BuildRequires:  pkgconfig(x11)
BuildRequires:  kdelibs-devel
BuildRequires:  cmake

%description
%{summary}.

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%cmake .  \
    %{cmake_kde_options}

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post

%files
%defattr(-,root,root,-)
# >> files
%{_kde_modulesdir}/*.so
%{_kde_servicesdir}/*.desktop
%{_kde_appsdir}/plasma-applet-frame/
# << files
